#! /bin/bash

ITERATIONS=20
CURR_BRIGHT=$(cat /sys/class/backlight/intel_backlight/brightness)
MAX_BRIGHT=$(cat /sys/class/backlight/intel_backlight/max_brightness)
MIN_BRIGHT=1

inc_backlight () {

	if [ $1 = "auto" ]; then
		inc=$(expr $MAX_BRIGHT / $ITERATIONS)
	else
		inc=$1
	fi

	result=$(expr $CURR_BRIGHT + $inc)

	if [ "$result" -gt "$MAX_BRIGHT" ]; then
		result=$MAX_BRIGHT
	elif [ "$result" -lt "$MIN_BRIGHT" ]; then
		result=$MIN_BRIGHT
	fi

	# Increase brightness
	echo "$result" | sudo tee '/sys/class/backlight/intel_backlight/brightness'
}

dec_backlight () {

	if [ $1 = "auto" ]; then
		dec=$(expr $MAX_BRIGHT / $ITERATIONS)
	else
		dec=$1
	fi

	result=$(expr $CURR_BRIGHT - $dec)

	if [ "$result" -gt "$MAX_BRIGHT" ]; then
		result=$MAX_BRIGHT
	elif [ "$result" -lt "$MIN_BRIGHT" ]; then
		result=$MIN_BRIGHT
	fi

	# Decrease brightness
	echo "$result" | sudo tee '/sys/class/backlight/intel_backlight/brightness'
}

print_help () {
	echo 'Usage: brightness [OPTIONS]'
	echo 'Arguments:'
	echo '-inc x               Increment brightness by "x", if x=="auto",'
	echo '                         then increment automatically'
	echo '-dec x               Decrement brightness by "x", if x=="auto",'
	echo '                         then decrement automatically'
	echo '-h                   Print this help and exit'
}

while [ $1 ]
do
	if [ $1 == "-inc" ]; then
		shift
		inc_backlight $1
	elif [ $1 == "-dec" ]; then
		shift
		dec_backlight $1
	elif [ $1 == "-h" ]; then
		print_help
	fi

	shift
done
