#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

primary=$(xrandr --query | grep " connected " | awk -F" " ' NR==1 { print $1 } ')
secondary=$(xrandr --query | grep " connected " | awk -F" " ' NR==2 { print $1 } ')

black="#282828"
white="#ebdbb2"
gray="#1d2021"
aqua="#689d68"

options="Extend Right (ER)\n"
options+="Extend Left (EL)\n"
options+="Duplicate (D)\n"
options+="Kill (K)\n"

height="$(echo -e "$options" | wc -l)"
colors="-nb $black -nf $white -sf $gray -sb $aqua"
output=$(echo -ne "$options" | dmenu -i -l $height -p "Secondary output:" $colors)

case "$output" in
  "Extend Right (ER)") xrandr --output "$secondary" --auto --right-of "$primary" ;;
  "Extend Left (EL)")  xrandr --output "$primary" --auto --right-of "$secondary" ;;
  "Duplicate (D)")     xrandr --output "$secondary" --auto --same-as "$primary"  ;;
  "Kill (K)")          xrandr --output "$secondary" --auto --off                 ;;
esac
