#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

# Ascii art (big font) from:
# https://www.ascii-art-generator.org

# Colors
RED="\e[31m"
GREEN="\e[32m"
BLUE="\e[34m"
BOLD="\e[1m"
RESET="\e[0m"
ULINE="\e[4m"

print_banner () {
  echo -ne "$BOLD""$RED"
  echo "****************************************"
  echo "*       _       _    __ _ _            *"
  echo "*      | |     | |  / _(_) |           *"
  echo "*    __| | ___ | |_| |_ _| | ___  ___  *"
  echo "*   / _\` |/ _ \\| __|  _| | |/ _ \\/ __| *"
  echo "*  | (_| | (_) | |_| | | | |  __/\\__ \\ *"
  echo "* (_)__,_|\\___/ \\__|_| |_|_|\\___||___/ *"
  echo "*                                      *"
  echo "****************************************"
  echo ""
  echo -ne "$RESET"
}

usage () {
  echo -e "$BOLD""NAME""$RESET"
  echo "    autogen - tool for keeping all my dotfiles in one place"
  echo ""
  echo -ne "$BOLD"
  echo "SYNOPSIS"
  echo -e "    autogen""$RESET"" [""$ULINE""OPTION""$RESET""] ..."
  echo -ne "$RESET""$BOLD"
  echo ""
  echo -e "DESCRIPTION""$RESET"
  echo "    Create a bunch of symbolic links for my dotfiles (e.g. .vim/,"
  echo "    files found in .config/). Allows system configuration to become"
  echo "    device agnostic"
  echo ""
  echo "    Possible arguments include:"
  echo ""
  echo -e "    ""$BOLD""vim""$RESET"
  echo "        Adds configuration files for Vim."
  echo ""
  echo -e "    ""$BOLD""bash""$RESET"
  echo "        Adds .bashrc to "'$HOME'"."
  echo ""
  echo -e "    ""$BOLD""i3""$RESET"
  echo "        Adds configuration files for the i3 window manager, inside"
  echo "        the \""'$HOME'"/.config/\" direcorty."
  echo ""
  echo -e "    ""$BOLD""i3blocks""$RESET"
  echo "        Adds configuration files for the i3blocks status bar, inside"
  echo "        the \""'$HOME'"/.config/\" direcorty."
  echo ""
  echo -e "    ""$BOLD""scripts""$RESET"
  echo "        Adds scripts to automate tasks. Scripts include:"
  echo ""
  echo -e "        ""$BOLD""brightness""$RESET"
  echo "            Script for changing the brightness of the primary"
  echo "            display from the terminal."
  echo ""
  echo -e "        ""$BOLD""cleanup""$RESET"
  echo "            Script for updating packages using the apt"
  echo "            package manager."
  echo ""
  echo -e "        ""$BOLD""screen""$RESET"
  echo "            Script for updating secondary display using dmenu."
  echo ""
  echo -e "    ""$BOLD""full""$RESET"
  echo "        Adds all possible options."
  echo ""
  echo -e "    ""$BOLD""-h, --help""$RESET"
  echo "        Display this help and exit."
  echo ""
  echo -e "$BOLD""AUTHOR""$RESET"
  echo "    Written by Jarrod Cameron."
}

# If no args
if [ -z $1 ]; then
  usage
  exit 0
fi

options=""
for arg in "$@"; do
  case "$arg" in
    "vim")      options+="{vim}"      ;;
    "i3")       options+="{i3}"       ;;
    "i3blocks") options+="{i3blocks}" ;;
    "bash")     options+="{bash}"     ;;
    "scripts")  options+="{scripts}"  ;;
    "full")     options+="{full}"     ;;
    *) usage ; exit 0                 ;;
  esac
done

print_banner

# Link the vim stuff
if [ "$(grep -E "{full}|{vim}" <<< "$options")" ]; then
  src="$HOME""/.dotfiles/files/vim"
  dst="$HOME""/.vim"
  rm -f "$dst"
  ln -s "$src" "$dst"
  echo -e "$GREEN""Successfully added: ""$BOLD""Vim config""$RESET"
fi

# Link the i3 window manager
if [ "$(grep -E "{full}|{i3}" <<< "$options")" ]; then
  mkdir "$HOME""/.config/" -p
  src="$HOME""/.dotfiles/files/i3" 
  dst="$HOME""/.config/i3"
  rm -f "$dst"
  ln -s "$src" "$dst"
  echo -e "$GREEN""Successfully added: ""$BOLD""i3wm config""$RESET"
fi

# link the i3blocks
if [ "$(grep -E "{full}|{i3blocks}" <<< "$options")" ]; then
  mkdir "$HOME""/.config/" -p
  src="$HOME""/.dotfiles/files/i3blocks" 
  dst="$HOME""/.config/i3blocks"
  rm -f "$dst"
  ln -s "$src" "$dst"
  echo -e "$GREEN""Successfully added: ""$BOLD""i3blocks config""$RESET"
fi

# link bashrc
if [ "$(grep -E "{full}|{bash}" <<< "$options")" ]; then
  src="$HOME""/.dotfiles/files/bashrc" 
  dst="$HOME""/.bashrc"
  rm -f "$dst"
  ln -s "$src" "$dst"
  echo -e "$GREEN""Successfully added: ""$BOLD""bash config""$RESET"
fi

# link scripts
if [ "$(grep -E "{full}|{scripts}" <<< "$options")" ]; then
  src="$HOME""/.dotfiles/files/scripts" 
  dst="$HOME""/.scripts"
  rm -f "$dst"
  ln -s "$src" "$dst"
  echo -e "$GREEN""Successfully added: ""$BOLD""scripts""$RESET"
fi
