#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   12/09/19 14:04

echo 'Usage: dlsym /path/to/libc'

readelf -Ws "$1" | perl -n -e '/: (\w*).*?(\w+)@@GLIBC_/ && print "$2 $1\n"'
strings -a -t x "$1" | grep '/bin/sh' | head -n1

