#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   29/03/20 15:25

# Get the most recent core dump from our boy systemd

# Exit on non-zero return status
set -e

CORES_LOC='/var/lib/systemd/coredump/'

coredump="$(find "$CORES_LOC" -type f -exec stat --format '%Y %n' "{}" \; \
	| sort -nr \
	| head -n1 \
	| awk '{print $2}')"

lz4 -d "$coredump" core




