#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   13/06/19 19:38

MANUALS_PATH="$HOME""/Documents/manuals"

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

height="$(ls "$MANUALS_PATH" | wc -l)"

pdf="$( ls "$MANUALS_PATH" | dmenu -p "Manual:" -i -l "$height" $COLORS )"

[ -z "$pdf" ] && exit 1

evince "$MANUALS_PATH""/""$pdf"





