#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   31/12/19 17:49

if [ -z "$1" ]; then
    printf 'Usage: rtac <binary>\n'
    exit 1
fi

wm_pid=$(xprop | grep _NET_WM_PID | sed 's/.* = //g')
bin_pid=$(pstree $wm_pid -p | head -n 1 | sed 's/^.*(//g ; s/)//g')

r2 -c 'dp='"$bin_pid" "$1"

#wm_pid="$(xprop | grep _NET_WM_PID | sed 's/.* = //g')"
#bin_pid="$(pstree $wm_pid -p | head -n 1 | sed 's/^.*(//g ; s/)//g')"
#rarun2_tty="$(readlink /proc/"${bin_pid}"/fd/0)"
#bin_name="$(cat /proc/"${bin_pid}"/cmdline | cut -c 11- -)"
#
#r2 -R stdio="${rarun2_tty}" -d "$bin_name" $@
#
#kill -9 "$bin_pid" &>/dev/null

