#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   05/05/19 19:28

# Colors used for the man page
export LESS_TERMCAP_mb=$(printf '\e[1;34m')
export LESS_TERMCAP_md=$(printf '\e[1;34m')
export LESS_TERMCAP_me=$(printf '\e[0m')
export LESS_TERMCAP_se=$(printf '\e[0m')
export LESS_TERMCAP_so=$(printf '\e[1;44;33m')
export LESS_TERMCAP_ue=$(printf '\e[0m')
export LESS_TERMCAP_us=$(printf '\e[1;32m')

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

max_len="$(man -k '.' | awk '
  BEGIN {
    max_len = 0;
    FS=" "
  }
  {
    if (length($1) + length ($2) > max_len) {
      max_len = length($1) + length ($2)
    }
  }
  END {
    print max_len
  }
')"

max_len=$(( max_len+2 ))

name="$(man -k '.' | awk '
BEGIN { FS=" " }
{
  printf "%-'$max_len's-->", $1 " " $2
  for (i=4; i<=NF; i++) {
    printf " %s ", $i
  }
  printf "\n"
}
' | dmenu -i -l 30 $COLORS | awk -F" " '{ print $2 " " $1 }' \
  | sed 's/[()]//g' )"

cmd="man $name"

urxvt -name "dropdown_manual" -e $cmd
