#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   25/08/19 11:29

# Reads the boomarks from the file in the secret directory
# The format of the file is:
# +----------+
# | name1    |
# | url1     |
# | name2    |
# | url2     |
# | ...      |
# | nameN    |
# | urlN     |
# +----------+
# TODO: Add book marks to file

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

SECRET_DIR="$HOME""/.dotfiles/secret"
SECRET_FILE="$SECRET_DIR""/bookmarks.txt"

max_len="$(awk '\
    BEGIN {
        max_len = 0;
    }
    NR%2==0 {
        // Skip odd lines
        next
    }
    {
        if (length($0) > max_len) {
            max_len = length($0)
        }
    }
    END {
        print max_len + 1
    }
' "$SECRET_FILE")"

n_bmarks="$(echo `awk 'END{print NR}' "$SECRET_FILE"` ' / 2' | bc)"

url="$(awk '\
    {
        name=$0;
        getline;
        url=$1;
        printf "%-'$max_len's--> %s\n", name, url;
    }
\' "$SECRET_FILE" | sort -d -f | dmenu -i -l "$n_bmarks" -p "Open bookmark:" $COLORS | sed 's/^.* --> //')"

if [ ! -z "$url" ]
then
    firefox -private -new-window "$url"
fi
