#!/bin/sh

echo ''
echo '#######################'
echo '#   sudo apt update   #'
echo '#######################'
sudo apt update --assume-yes

echo ''
echo '########################'
echo '#   sudo apt upgrade   #'
echo '########################'
sudo apt upgrade --assume-yes


echo ''
echo '###########################'
echo '#   sudo apt autoremove   #'
echo '###########################'
sudo apt autoremove --assume-yes

echo ''
