#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)
# Date:   24/12/19  8:17

SESSION="radare2_debug"

if [ -z "$1" ]; then
    printf "Usage: d2 </path/to/a.out>\n" >&2
    exit 1
fi

win_name="./${prog_name}"
cmd="bash ~/.scripts/.tmux/d2_spawn.sh "${prog_name}""

# If there is an already running session kill it
function kill_open_session () {
    if tmux ls | grep "^${SESSION}: "; then
        tmux kill-session -t "$SESSION"
    fi
}

kill_open_session &>/dev/null

tmux new-session -d -s "$SESSION" -n "$win_name" "${cmd}"

tmux attach-session -t "${SESSION}"
