#!/bin/sh

# Author: Jarrod Cameron (z5210220)

[ -z "$EDITOR" ] && EDITOR="$(which vim)"
[ -z "$TERMINAL" ] && TERMINAL="$(which st)"

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

get_file () {
  local FULL_PATH="$1"
  local OPTIONS="$(ls $FULL_PATH)"
  local HEIGHT="$(echo "$OPTIONS" | wc -l)"
  local OUTPUT="$(echo "$OPTIONS" | dmenu -i -l $HEIGHT -p "Edit file:" $COLORS)"

  if [ -z "$OUTPUT" ]; then
    exit 1
  fi

  echo $OUTPUT
}

options=".vimrc\ni3-gaps\ni3blocks\n.bashrc\n.Xresources\n.gdbinit\ncompton\ntodo\nsuckless ->\nhome_scripts ->\ni3blocks_scripts ->"

height="$(echo $options | wc -l)"
output=$(echo "$options" | dmenu -i -l $height -p "Edit file:" $COLORS)

FULL_PATH=""
case "$output" in
  "home_scripts ->")     FULL_PATH="$HOME""/.scripts/" ;;
  "i3blocks_scripts ->") FULL_PATH="$HOME""/.config/i3blocks/scripts/" ;;
  "suckless ->")         FULL_PATH="$HOME""/.dotfiles/suckless/" ;;
esac

cmd=""
case "$output" in
  "i3-gaps")     cmd="$EDITOR "$HOME"/.config/i3/config"                      ;;
  "i3blocks")    cmd="$EDITOR "$HOME"/.config/i3blocks/config"                ;;
  ".vimrc")      cmd="$EDITOR "$HOME"/.vim/vimrc"                             ;;
  ".bashrc")     cmd="$EDITOR "$HOME"/.bashrc"                                ;;
  ".Xresources") cmd="$EDITOR "$HOME"/.Xresources"                            ;;
  "compton")     cmd="$EDITOR "$HOME"/.config/compton/config"                 ;;
  "todo")        cmd="$EDITOR "$HOME"/.todo"                                  ;;
  ".gdbinit")    cmd="$EDITOR "$HOME"/.gdbinit"                               ;;
  "suckless ->")         cmd="$EDITOR ""$FULL_PATH""$(get_file "$FULL_PATH")" ;;
  "home_scripts ->")     cmd="$EDITOR ""$FULL_PATH""$(get_file "$FULL_PATH")" ;;
  "i3blocks_scripts ->") cmd="$EDITOR ""$FULL_PATH""$(get_file "$FULL_PATH")" ;;
  *)             exit 1 ;;
esac

$TERMINAL -e $cmd
