#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   28/05/19 19:40

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

BM_PATH="$HOME""/.config/google-chrome/Default/Bookmarks"

max_len="$(jq ".roots.bookmark_bar.children[] | .name" "$BM_PATH" | awk '
        BEGIN {
            max_len = 0;
            FS=" "
        }
        {
            if (length($0) > max_len) {
                max_len = length($0)
            }
        }
        END {
            print max_len
        }
    ')"

n_bmarks="$(jq ".roots.bookmark_bar.children[] | .name" $BM_PATH | wc -l)"

jq ".roots.bookmark_bar.children[] | .name, .url" "$BM_PATH" | sed 's/^"\s*// ; s/\s*"$//' | awk '
{
    printf "%s\n", $0
    getline
    printf "%s\n", $0
}
'

exit 0

url="$(jq ".roots.bookmark_bar.children[] | .name, .url" "$BM_PATH" | sed 's/^"\s*// ; s/\s*"$//' | awk '
{
    printf "%-'$max_len's-->  ", $0
    getline
    printf "%s\n", $0
}
' | sort -d -f | dmenu -i -l "$n_bmarks" -p "Open bookmark:" $COLORS | sed 's/^.* -->  //')"

if [ -z "$url" ]; then
  exit 1
fi

google-chrome --new-window "$url"
