#!/bin/bash

# Author: Jarrod Cameron (z5210220)

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

eval $(xrandr --query | awk '
BEGIN {
  FS=" ";
  count=0
}
/connected/ {
  printf "output_%d=%s ;\n", count, $1
  count++
}
END {
  printf "n_output=%d ;\n", count
}')

primary="$output_1"
secondary="$output_2"

options="Extend Right (ER)\nExtend Left (EL)\nDuplicate (D)\nKill (K)"

height="$(echo -e "$options" | wc -l)"
output="$(echo -ne "$options" | dmenu -i -l $height -p "Secondary output:" $COLORS)"

case "$output" in
  "Extend Right (ER)") xrandr --output "$secondary" --auto --right-of "$primary" ;;
  "Extend Left (EL)")  xrandr --output "$primary" --auto --right-of "$secondary" ;;
  "Duplicate (D)")     xrandr --output "$secondary" --auto --same-as "$primary"  ;;
  "Kill (K)")          xrandr --output "$secondary" --auto --off                 ;;
esac

# Sometimes background won't load on secondary display
# Choose a random wallpaper
feh --bg-scale $(ls ~/Pictures/wallpapers/*.png | shuf | head -n 1)
