#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

black="#282828"
white="#ebdbb2"
gray="#1d2021"
aqua="#689d68"

options="Leetcode\n"
options+="Office 365\n"
options+="Google\n"
options+="Youtube\n"
options+="Webcms3\n"
options+="Facebook\n"
options+="myUNSW\n"

colors="-nb $black -nf $white -sf $gray -sb $aqua"
output="$(echo -ne "$options" | dmenu -i -p "Search:" $colors)"

#google-chrome --new-window "http://www.google.com/search?q=test string"

url=""
case "$output" in
  "Leetcode")   url="https://leetcode.com/"                    ;;
  "Office 365") url="https://www.office.com/"                  ;;
  "Google")     url="https://www.google.com/"                  ;;
  "Youtube")    url="https://www.youtube.com/"                 ;;
  "Webcms3")    url="https://webcms3.cse.unsw.edu.au/"         ;;
  "Facebook")   url="https://www.facebook.com/"                ;;
  "myUNSW")     url="https://my.unsw.edu.au/"                  ;;
  *)            url="http://www.google.com/search?q=""$output" ;;
esac

google-chrome --new-window "$url"
