#!/bin/sh

# Author: Jarrod Cameron (z5210220)
# Date:   10/05/19  8:50

# Uses dmenu to get input and them opens that search term
#   as if it was typed in at youtube.com

BLACK="#282828"
WHITE="#ebdbb2"
GRAY="#1d2021"
AQUA="#689d68"
COLORS="-nb $BLACK -nf $WHITE -sf $GRAY -sb $AQUA"

# Kinda strange but yeah
input="$(cat << EOF | dmenu -p 'YouTube search:' $COLORS )"
EOF

[ -z "$input" ] && exit 0

vid="$(echo -n "$input" | sed 's/^\s*//g ; s/\s*$//g ; s/ /+/g')"
url="https://www.youtube.com/results?search_query=""$vid"
google-chrome --new-window "$url"
