#!/bin/sh

# Author: Jarrod Cameron (z5210220)

# NOTE: Using `entr' to wait for the files to update doesn't work.
#       I assume this is because the files are generated when
#       being read.

FOREGROUND=282828
BACKGROUND=458588

min () {
  if [ "$1" -lt "$2" ]; then
    echo "$1"
  else
    echo "$2"
  fi
}

# Remaining battery level
level=$(cat /sys/class/power_supply/BAT0/capacity)
level="$(min "${level}" 100)"

if [ "$(cat /sys/class/power_supply/BAT0/status)" = "Discharging" ]; then
  TEXT="Battery: $level""%"
else
  TEXT="Charging: $level%"
fi

echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
