#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

# Pick color depending on remaining battery
# Colors are picked from:
#   https://mycolor.space/gradient3
# Selected colors:
# - 00FF00 (Green)
# - 00FF00 (Green)
# - FF0000 (Red)
get_color () {

  # Battery level
  level=$(sed 's/%//g' <<< "$bat")

  if [ $level -le "8" ]; then
    retval="ff0000"
  elif [ $level -le "16" ]; then
    retval="f36300"
  elif [ $level -le "25" ]; then
    retval="de9200"
  elif [ $level -le "33" ]; then
    retval="c2b700"
  elif [ $level -le "41" ]; then
    retval="a0d600"
  elif [ $level -le "50" ]; then
    retval="8ae400"
  elif [ $level -le "58" ]; then
    retval="67f100"
  else
    retval="00ff00"
  fi

  # Return the color
  echo $retval

}

# Remaining battery level
bat=$(acpi | awk '/^Battery 0/ {print $4}' | sed 's/,//g')

if [ !  -z "$(acpi | grep "Charging")" ]; then
  echo "Charging: $bat" # Long text
  echo "Chr: $bat"      # Short text
else
  echo "Battery: $bat" # Long text
  echo "Bat: $bat"     # Short text
fi

echo \#$(get_color)

