#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

open_cal () {
  halt='read -sn 1 -p "Press any key to close...";'
  cal='cal -y;'

  urxvt -name dropdown_editor -e sh -c "vim test.c"
  #urxvt -name "dropdown_cal" -e bash -c "$cal""$halt"
}

text="$(date '+%d-%m-%Y %I:%M %p')"
echo "$text"        # Long text
echo "$text"        # short text
echo \#00AAFF       # Color

case $BLOCK_BUTTON in
  1) open_cal  ;;  # Left click
  2) open_cal  ;;  # Scroll click
  3) open_cal  ;;  # Right click
esac

