#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

# Returns the average temperature of the cpu cores
get_temp () {
  temps="$(sensors | awk '/^Core / { print $3 }' | sed 's/[+°C]//g')"
  total="0"
  for t in $temps; do
    total=$(echo "scale=1; $total + $t" | bc)
  done
  num=$(echo "$temps" | wc -l)
  mean=$(echo "scale=1; $total / $num" | bc)

  # Return mean core temperature
  echo "$mean"
}

# Returns average cpu usage
get_usage () {
  idle=$(mpstat 1 1 | awk '/Average:/ {print $12}')
  echo "$(echo "scale=2; 100 - $idle" | bc)"
}

# Pick color depending on CPU usage
# Colors are picked from:
#   https://mycolor.space/gradient3
# Selected colors:
# - 00FF00 (Green)
# - FFFF00 (Yellow)
# - FF0000 (Red)
get_color () {

  # Easier to compare integer values
  int_usage=$(python3 -c "print (int (float ("$usage")))")

  if [ $int_usage -le "8" ]; then
    retval="00ff00"
  elif [ $int_usage -le "16" ]; then
    retval="6dff00"
  elif [ $int_usage -le "25" ]; then
    retval="9aff00"
  elif [ $int_usage -le "33" ]; then
    retval="bdff00"
  elif [ $int_usage -le "41" ]; then
    retval="dbff00"
  elif [ $int_usage -le "50" ]; then
    retval="eaef00"
  elif [ $int_usage -le "58" ]; then
    retval="f6e000"
  elif [ $int_usage -le "66" ]; then
    retval="ffd000"
  elif [ $int_usage -le "75" ]; then
    retval="ffad00"
  elif [ $int_usage -le "83" ]; then
    retval="ff8700"
  elif [ $int_usage -le "91" ]; then
    retval="ff5b00"
  else
    retval="ff0000"
  fi

  # Return the color
  echo $retval

}

# Display info about CPU usage
notify () {
  max="$(lscpu | grep "^CPU max MHz:" | sed 's/CPU max MHz: *//g; s/\..*$//g')"

  results="$(ps -e ch -o "pid cmd %cpu" --sort=-%cpu | awk -F" " 'NR<11 { printf "   %d: %s (%.1f%%)\n", $1, $2, $3}' -)"

  notify-send --expire-time=10000 "\

    <span font='20px'><b>CPU Summary</b></span>
    <span font='15px'>Max:   $max MHz</span>
    <span font='15px'>Usage: "$usage"%</span>
    <span font='15px'>Temp:  "$temp"°C</span>

<span font='15px'>$results</span>
"

}

usage=$(get_usage)
temp=$(get_temp)
text="CPU: ""$usage""% (""$temp""°C)"

case $BLOCK_BUTTON in
  1) notify        ;;& # Left click
  2) notify        ;;& # Scroll click
  3) notify        ;;& # Right click
esac

echo "$text"     # Long text
echo "$text"     # Short text
echo \#$(get_color)
