#!/bin/sh

# Author: Jarrod Cameron (z5210220)

FOREGROUND=282828
BACKGROUND=458588

# Returns the average temperature of the cpu cores
get_temp () {
  temps="$(sensors | awk '/^Core / { print $3 }' | sed 's/[+°C]//g')"
  total="0"
  for t in $temps; do
    total=$(echo "scale=1; $total + $t" | bc)
  done
  num=$(echo "$temps" | wc -l)
  mean=$(echo "scale=1; $total / $num" | bc)

  # Return mean core temperature
  echo "$mean"
}

# Returns average cpu usage
get_usage () {
  idle=$(mpstat 1 1 | awk '/Average:/ {print $12}')
  echo "$(echo "scale=2; 100 - $idle" | bc)"
}

# Display info about CPU usage
notify () {
  max="$(lscpu | grep "^CPU max MHz:" | sed 's/CPU max MHz: *//g; s/\..*$//g')"

  results="$(ps -e ch -o "pid cmd %cpu" --sort=-%cpu | awk -F" " 'NR<11 { printf "   %d: %s (%.1f%%)\n", $1, $2, $3}' -)"

  notify-send --expire-time=10000 "\

    <span font='20px'><b>CPU Summary</b></span>
    <span font='15px'>Max:   $max MHz</span>
    <span font='15px'>Usage: "$usage"%</span>
    <span font='15px'>Temp:  "$temp"°C</span>

<span font='15px'>$results</span>
"

}

usage=$(get_usage)
temp=$(get_temp)
TEXT="CPU: ""$usage""% (""$temp""°C)"

case $BLOCK_BUTTON in
  1) notify        ;; # Left click
  2) notify        ;; # Scroll click
  3) notify        ;; # Right click
esac

echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
