#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

# Recall: `exit 1` will prevent the module from being displayed

BACKGROUND=689d6a
FOREGROUND=282828

function abort () {
  err_msg="$1"
#  notify-send --expire-time=10000 "$err_msg"
  echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $err_msg </span>"
  echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $err_msg </span>"
  exit 0
}

# Check number of interfaces (not including loopback interface)
# Exit if no other interface detected
[ "$(ls /sys/class/net | grep -v "lo" | wc -l)" = "0" ] && abort "Not interface/s detected"

# BUG: use '/sys/class/net' to detect interface
interface="$(ip route | awk '/^default/ {print $5}')"

# Exit if no active interface
[ -z "$interface" ] && abort "No active interface"

# Exit if networking is disabled
[ "$(nmcli networking)" = "disabled" ] && abort "Networking is disabled on: ""$interface"

# Exit if interface is closed
[ "$(cat /sys/class/net/"$interface"/operstate)" = "down" ] && "Interface ("$interface") is closed"

# IPv4 address with domain mask
ipv4="$(ip addr show $interface | awk '/^\s*inet / {print $2}')"

# Signal quality
# For more information see (4.1 /proc/net/wireless):
# https://hewlettpackard.github.io/wireless-tools/Linux.Wireless.Extensions.html
quality=$(cat /proc/net/wireless | grep "^""$interface" | awk '{print $4}' | sed 's/[-.]//g')

# The network name
SSID="$(iwconfig "$interface" | grep "ESSID" | sed 's/.*ESSID:"//g; s/".*//g')"

TEXT="$SSID"": ""$ipv4"" (""$quality""%)"

echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
echo "<span background='#${BACKGROUND}' foreground='#${FOREGROUND}'> $TEXT </span>"
