" Vim Configuration File
"        _
"       (_)
" __   ___ _ __ ___  _ __ ___
" \ \ / / | '_ ` _ \| '__/ __|
"  \ V /| | | | | | | | | (__
"   \_/ |_|_| |_| |_|_|  \___|
 
" spell-check set to F6
map <F6> :setlocal spell! spelllang=en_eu<CR>

" Toggle the grey bar thing
map <F8> :call ToggleCC()<CR>

syntax enable
syntax on

set t_Co=256 
set background=dark
colorscheme gruvbox 

set tabstop=2
set shiftwidth=4
set numberwidth=4
set smartindent
set autoindent
set showcmd
set wildmenu

" Display current line number
set number 

" Why are your numbers weird?
set relativenumber

" Spaces (not tabs)
set expandtab

" Disable error bell
set belloff=all

" Set the <leader> to ","
let mapleader=","

" Leave 3 lines above/beloc cursor
set scrolloff=3

" Highligh current line
set cursorline

" Go to start/end of line in insert mode
inoremap <leader>a <esc>A
inoremap <leader>i <esc>I

" Edit + reload vimrc anytime
nnoremap <leader>ev :tabnew $MYVIMRC<CR>
nnoremap <leader>rv :source $MYVIMRC<CR>

" Duplicate current line
nnoremap <leader>p Vyp
inoremap <leader>p <esc>Vyp

" Useless help menu is mapped to <esc>
nnoremap <F1> <esc>
inoremap <F1> <esc>

" <space>, <enter> and <backspace> keys that actually work
nnoremap <cr> o<esc>
nnoremap <space> i<space><esc>l

" Yank the whole line
nnoremap yy Vy

" Yank/paste to the system keyboard
vnoremap Y :'<,'>:w !xclip -selection clip <CR><CR>
nnoremap P :r !xclip -selection clip -out<CR>

" Convert word to upper case, not recursive
inoremap <c-u> <esc>mxviwu`xa
nnoremap <c-u> <esc>mxviwu`x
inoremap <leader>u <esc>mxviwu`xa
nnoremap <leader>u <esc>mxviwu`x

" Nice
nnoremap j j<c-g>
nnoremap k k<c-g>
nnoremap <up> <up><c-g>
nnoremap <down> <down><c-g>

" ???
set backspace=indent,eol,start
set backspace=2

autocmd VimEnter * echo "\"Talk is cheap. Show me the code\" - Linus Torvalds."

" maps "WQ" to ":wq"
command! -nargs=* WQ :wq <args>
command! -nargs=* Wq :wq <args>
command! -nargs=* W  :w <args>
command! -nargs=* Q  :q <args>
command! -nargs=* Vsp  :vsp <args>
command! -nargs=* VSp  :vsp <args>
command! -nargs=* VSP  :vsp <args>
command! -nargs=* Sp  :sp <args>
command! -nargs=* SP  :sp <args>

" urxvt only
" IBeam -> Insert
" Underline -> replace
" Block -> Normal
let &t_SI = "\<Esc>[6 q"
let &t_SR = "\<Esc>[4 q"
let &t_EI = "\<Esc>[2 q"

" Shows the tabs
set list listchars=tab:>-

" Opens the terminal vertical
command! T :vertical terminal

" Skeletons
autocmd BufNewFile *.c 0r ~/.vim/templates/c.skel | %s/==DATE==/\=substitute(system('date +"%x %k:%M"'),'\n','','g')/g | %s/==NAME==/Jarrod Cameron (z5210220)/g | 13
autocmd BufNewFile *.cpp 0r ~/.vim/templates/cpp.skel | %s/==DATE==/\=substitute(system('date +"%x %k:%M"'),'\n','','g')/g | %s/==NAME==/Jarrod Cameron (z5210220)/g | 8
autocmd BufNewFile Makefile 0r ~/.vim/templates/make.skel | 7
autocmd BufNewFile *.sh 0r ~/.vim/templates/bash.skel | 5
autocmd BufNewFile *.rmd 0r ~/.vim/templates/rmd.skel | 9
autocmd BufNewFile *.html 0r ~/.vim/templates/html.skel | 7
autocmd BufNewFile *.py 0r ~/.vim/templates/py.skel | 4

" Turn on hlsearch when searching
" Turn it off in insert mode
nnoremap / :set hlsearch<cr>/
nnoremap ? :set hlsearch<cr>?
nnoremap n :set hlsearch<cr>n
nnoremap N :set hlsearch<cr>N
nnoremap # :set hlsearch<cr>#
nnoremap * :set hlsearch<cr>*
autocmd InsertEnter * set nohlsearch

" Reload Xresources after writing to file
" NOTE: errors are omitted
"autocmd BufWritePost .Xresources silent: !xrdb .Xresources
"autocmd BufWritePost ~/.config/i3/config silent: !i3-msg restart
"autocmd BufWritePost ~/.config/i3blocks/config silent: !i3-msg restart

autocmd BufWritePost ~/.vim/vimrc :source $MYVIMRC

autocmd FileType c iabbrev \N \n
autocmd FileType c iabbrev \m \n
autocmd FileType c iabbrev struc struct
autocmd FileType c inoremap {<CR> {<CR>}<esc>O

autocmd FileType cpp inoremap {<CR> {<CR>}<esc>O

autocmd FileType rmd command! R :w | :!clear && Rscript -e "rmarkdown::render('%')" && xdg-open %<.pdf
autocmd FileType rmd command! C :w | :!clear && Rscript -e "rmarkdown::render('%')"
autocmd FileType rmd command! O :!clear && xdg-open %<.pdf
autocmd FileType rmd iabbrev tbf textbf
autocmd FileType rmd iabbrev tit textit

autocmd FileType tex command! C :w | :!clear && pdflatex %
autocmd FileType tex command! R :w | !clear && pdflatex % && xdg-open %<.pdf 

autocmd FileType html inoremap {<CR> {<CR>}<esc>O
autocmd FileType html inoremap <tr><CR> <tr><CR></tr><esc>O
autocmd FileType html inoremap <th><space> <th><space></th><esc>O
autocmd FileType html inoremap <td><space> <td><space></td><esc>O

iabbrev tehn then
iabbrev waht what
iabbrev wehn when
iabbrev teh the
iabbrev adn and
iabbrev si is
iabbrev nad and


" Alternate between a 79 character column
"   and hiding the column
fun! ToggleCC()
	if &cc == 0
		set colorcolumn=79
	else
		set colorcolumn=0
	endif
endfunction
