#!/usr/bin/env bash

# Author: Jarrod Cameron (z5210220)

primary=$(xrandr --query | grep " connected " | awk -F" " ' NR==1 { print $1 } ')
secondary=$(xrandr --query | grep " connected " | awk -F" " ' NR==2 { print $1 } ')

options="Extend Right (ER)\nExtend Left (EL)\nDuplicate (D)\nKill (K)\n"
output=$(echo -ne "$options" | dmenu -i -l 4 -p "Secondary output:")

if [[ ! -n "$output" ]]; then
  # Do nothing
  true

elif [ "$output" = "Extend Right (ER)" ]; then
  # Secondary output is on the RIGHT of the primary output
  xrandr --output "$secondary" --auto --right-of "$primary"

elif [ "$output" = "Extend Left (EL)" ]; then
  # Secondary output is on the LEFT of the primary output
  xrandr --output "$primary" --auto --right-of "$secondary"

elif [ "$output" = "Duplicate (D)" ]; then
  # Primary and secondary output are duplicated
  xrandr --output "$secondary" --auto --same-as "$primary"

elif [ "$output" = "Kill (K)" ]; then
  # Kill the secondary output
  xrandr --output "$secondary" --auto --off

fi
